version: '3.5'

x-env-vars: &env-vars
  POSTGRES_PASSWORD: "xpto@1234"
  POSTGRES_USER: lemoney
  POSTGRES_DB: lemoney
  SECRET_KEY_BASE: "ed084ad14e5cf6ad60599eac4a2aefe1f3def98677f455e60b344d5f28d3ef2bba4528973ed2e148ac7fdc1a1e5fae9c18cf87e7de2076e05c04bbfba39364f2"

services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      <<: *env-vars

  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    environment: 
      <<: *env-vars
      RAILS_ENV: production
    depends_on:
      - db

  dev:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    environment: 
      <<: *env-vars
      RAILS_ENV: development
    depends_on:
      - db

  test:
    build: .
    volumes:
      - .:/opt/app
    environment: 
      <<: *env-vars
      RAILS_ENV: test
    depends_on:
      - db
